### ISSUE TITLE
Chameleon library dependency issues

### ISSUE THREAD

**Issue by Ristovski** [jaquadro/GardenStuff#1]
This project depends on the 1.12 version of `Chameleon` as stated by `evaluationDependsOn(":..:Chameleon-${minecraft_base_version}")`

The issue is, `:..:` is not a valid path specifier, nor a valid name afaik.
This also seems to be including the `Chameleon` library as a sub-project rather than a library.
If this is intended, I would propose adding `Chameleon` as a git submodule instead.
If not, a simple way of loading it from a `libs/` folder would suffice as it would give a clear indication it looks for the library there.

**Comment by jaquadro** [comment]
You'll need to be more clear about how you're using the gradle script.  This scheme has been working well for me for standard gradle build, and for setting up an IntelliJ project with both the mod and Chameleon included as modules.  That makes development much more convenient for me, with the pre-requisite that both projects are first checked out as directory peers.

**Comment by Ristovski** [comment]
Well, running `gradle build` (I have my own install of gradle) fails since it cant find `:..:Chameleon-1.12`.

I tried cloning the Chameleon repository in the root folder of GardenStuff as `Chameleon-1.12` and it didn't pick that up either. Even after removing the weird `:..:` in the path it still failed.

**Comment by Ristovski** [comment]
Is the `:..:` supposed to be `../`? 
`../Chameleon-1.12` would make much more sense than `:..:Chameleon-1.12` which clearly doesn't, and won't work.
