### ISSUE TITLE
Wrought Iron Ingots Not Stacking in Bloomery

### ISSUE THREAD

**Issue by sweetsosweet** [jaquadro/GardenStuff#3]
I'm using version GardenStuff-1.12-2.1.0.jar and I lost almost stack of iron ore because it seems like the bloomery isn't stacking the finished wrought iron ingots. Unless I take them out one by one, the ingots just seem to overwrite instead of stacking. :(

**Comment by katubug** [comment]
In my version, they don't even overwrite. Unless I remove each one individually, it produces one - then the next one produced DELETES the existing one, leaving the slot empty.

**Comment by TimGoll** [comment]
same happens to me. After about 3 months ... still not fixed

**Comment by TimGoll** [comment]
I'll fix it and open a pullrequest if @jaquadro accepts them

**Comment by SjetCraft** [comment]
Problem is in [TileBloomery] (https://github.com/jaquadro/GardenStuff/blob/master/src/com/jaquadro/minecraft/gardenstuff/block/tile/TileBloomeryFurnace.java#L138).

The fix should be simple.

**Comment by TimGoll** [comment]
yep. seen that. But @jaquadro seems to be absent

**Comment by SjetCraft** [comment]
Open a PR anyways, I'll try to find him on Discord to ask if he can pull it.
I'll open a separate PR for the Wrought Iron Block name issue.

**Comment by jaquadro** [comment]
Sorry yeah I would accept a PR.  

If you do submit one, post back to this issue.  GitHub notifications are kind of dumb and I won't receive a PR notification.

**Comment by SjetCraft** [comment]
Pull Request submitted.

I also fixed the Block of Wrought Iron name.

**Comment by SjetCraft** [comment]
@sweetsosweet PR has been merged and is now live on CurseForge. 
You can close this issue.
